package org.firstinspires.ftc.teamcode.config;

/**
 * Device names as configured on the Driver Station / Control Hub, kept in
 * sync with the Hardware Map Editor in FTC Code Utils. Use these constants
 * with hardwareMap.get(...) instead of retyping string literals.
 *
 * Generated by FTC Code Utils -- edit devices in the Hardware Map Editor,
 * not here.
 */
public final class HardwareNames {
    private HardwareNames() { }

    public static final String TEST_MOTOR = "testMotor"; // DcMotor, Control Hub, Port 0
    public static final String SIDE_SWEEPER_LEFT = "sideSweeperLeft"; // CRServo, Control Hub, Port 0
    public static final String SIDE_SWEEPER_RIGHT = "sideSweeperRight"; // CRServo, Control Hub, Port 1
} 